# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Klahanie Association
email: info@klahanie.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://klahanie.github.io/klahanie" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  klahanie
github_url: "https://github.com/klahanie/klahanie"
branch: "master"
paginate: 10

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-github-metadata
  
# Enable or disable heading anchors
heading_anchors: true

collections:  
  announcements:
    output: true
    url: announcements
  staff:
  board:
  neighborhoods:
    output: true
    url: neighborhoods
  discounts: 
    output: true
    url: discounts
  clubs:
    output: true
    url: clubs
  amenities: 
    output: true
    url: amenities
  magazine:
    output: true
    url: magazine

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - node_modules
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
#  - .gitignore
#  - readme.md
